server:    
    port: 81
    session:
        timeout: 1800

datasource:   #数据库连接
    url: jdbc:mysql://192.168.102.132:3306/lims_cloud?&useSSL=true
    username: root
    password: sunway123#
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
    #username: sa
    #password: 
    #driver-class-name: org.h2.Driver
    

# Initialize the schema on startup.
jpa:
    generate-ddl:  true
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
    hibernate.ddl-auto: none 